# Generated by Django 3.1.1 on 2020-10-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rekon', '0002_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
